name: "Podcast Generator"
author: "Priyanka Jacob"
description: "Generates a feed for the podcast from the yaml file"
runs: 
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: The committer's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}
